# 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY 1

# el 이 들어가는 동물
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE ('%el%') AND ANIMAL_TYPE = 'Dog'
GROUP BY 1, 2
ORDER BY 2

# 카테고리 별 상품
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY 1
ORDER BY 1

# 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, CASE WHEN SEX_UPON_INTAKE LIKE ('%Neutered%') THEN 'O'
                             WHEN SEX_UPON_INTAKE LIKE ('%Spayed%') THEN 'O'
                             ELSE 'X'
                        END
                        AS "중성화"
FROM ANIMAL_INS
ORDER BY 1

# DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d')
FROM ANIMAL_INS
ORDER BY 1

# 오랜 기간 보호한 동물(2)
SELECT I.ANIMAL_ID, I.NAME # , DATEDIFF(O.DATETIME, I.DATETIME)
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2

# 조건별 분류 주문상태 출력
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE,'%Y-%m-%d')
     , CASE WHEN OUT_DATE <= '2022-05-01' THEN '출고완료'
            WHEN OUT_DATE > '2022-05-01' THEN '출고대기'
            ELSE '출고미정'
            END 
            AS '출고여부'                        
FROM FOOD_ORDER
ORDER BY 1

# 취소되지 않은 예약 조회
SELECT APNT_NO, PT_NAME, APP.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM DOCTOR D
JOIN APPOINTMENT APP ON APP.MDDR_ID = D.DR_ID
JOIN PATIENT P ON P.PT_NO = APP.PT_NO
WHERE APNT_YMD LIKE "2022-04-13%"
    AND APNT_CNCL_YN = 'N'
    AND APP.MCDP_CD = 'CS'
ORDER BY 6