# 가장 비싼 명품
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT

# 최댓값 구하기
SELECT MAX(DATETIME) AS '시간'
FROM ANIMAL_INS

# 제일 비싼 식품 정보
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)

# 최솟값 구하기
SELECT MIN(DATETIME) AS '시간'
FROM ANIMAL_INS

# 동물 수 구하기
SELECT COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS

# 중복 제거하기
SELECT COUNT(DISTINCT(NAME)) AS 'count'
FROM ANIMAL_INS
WHERE NAME <> 'NULL'

